api/urls.py
from django.urls import path
from .views import HeartApiView, HeartApiViewDetails

urlpatterns = [
    path('heart-api/', HeartApiView.as_view(), name='heart-api'),
    path('heart-api-details/<str:pk>/', HeartApiViewDetails.as_view(), name='heart-api-details')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("api.urls")),
    path('',include('website.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'


urlpatterns = [
    path('', History.as_view(), name='history'),
    path('input-data/', InputData.as_view(), name='input-data'),
    path('prediction-results/<str:id>/', PredictionResults.as_view(), name='results'),
    path("delete-results/<str:result_id>/", delete_result, name="delete-result"),
]

templates/block/base-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>
    Argon Dashboard - Free Dashboard for Bootstrap 4 by Creative Tim
  </title>
  <!-- Favicon -->
  <!-- Fonts -->
  <link href="{% static "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" %}" rel="stylesheet">
  <!-- Icons -->
  <link href="{% static "./assets/js/plugins/nucleo/css/nucleo.css" %}" rel="stylesheet" />
  <link href="{% static "./assets/js/plugins/@fortawesome/fontawesome-free/css/all.min.css" %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static "assets/css/argon-dashboard.css" %}" rel="stylesheet" />
</head>

<body class="">
  <nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Collapse header -->
        <div class="navbar-collapse-header d-md-none">
          <div class="row">
            <div class="col-6 collapse-brand">
              
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <!-- Navigation -->
          <ul class="navbar-nav">
            <li class="nav-item {% if request.resolver_match.url_name == 'history' %}active{% endif %}">
                <a class="nav-link {% if request.resolver_match.url_name == 'history' %}active{% endif %}" href="{% url 'website:history' %}">
                    <i class="ni ni-folder-17 text-primary"></i> History
                </a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'input-data' %}active{% endif %}">
                <a class="nav-link {% if request.resolver_match.url_name == 'input-data' %}active{% endif %}" href="{% url 'website:input-data' %}">
                    <i class="ni ni-single-02 text-yellow"></i> Input Data
                </a>
            </li>
          </ul>      
      </div>
    </div>
  </nav>
 
  {% block content %}{% endblock content %}

      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          
        </div>
      </footer>
    </div>
  </div>
  <!--   Core   -->
  <script src="{% static "./assets/js/plugins/jquery/dist/jquery.min.js" %}"></script>
  <script src="{% static "./assets/js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js" %}"></script>
  <!--   Optional JS   -->
  <!--   Argon JS   -->
  <script src="{% static "./assets/js/argon-dashboard.min.js?v=1.1.2" %}"></script>
  <script src="{% static "https://cdn.trackjs.com/agent/v3/latest/t.js" %}"></script>
  <script>
    window.TrackJS &&
      TrackJS.install({
        token: "ee6fab19c5a04ac1a32a645abde4613a",
        application: "argon-dashboard-free"
      });
  </script>
</body>

</html>