api/urls.py
from django.urls import path
from .views import HeartApiView, HeartApiViewDetails

urlpatterns = [
    path('heart-api/', HeartApiView.as_view(), name='heart-api'),
    path('heart-api-details/<str:pk>/', HeartApiViewDetails.as_view(), name='heart-api-details')
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include("api.urls")),
    path('',include('website.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'


urlpatterns = [
    path('', History.as_view(), name='history'),
    path('input-data/', InputData.as_view(), name='input-data'),
    path('prediction-results/<str:id>/', PredictionResults.as_view(), name='results'),
    path("delete-results/<str:result_id>/", delete_result, name="delete-result"),
]

api/models.py
from django.db import models
import uuid
class HeartParameter(models.Model):
    SEX = [
        (0,'Male'),
        (1,'Female')
    ]

    CHEST_PAIN_TYPE = [
        (0,'Typical angina'),
        (1,'Atypical angina'),
        (2,'Non-anginal pain'),
        (3, 'Asymptomatic')
    ]

    #Categorized as above 120 mg/dl
    FASTING_BLOOD_SUGAR_LEVEL = [
        (0,'True'),
        (1,'False')
    ]

    RESTING_ELECTROCARDIOGRAPHOC_RESULTS = [
        (0,' Normal'),
        (1,'Having ST-T wave abnormality'),
        (2,'Showing probable or definite left ventricular hypertrophy')
    ]

    EXERCISE_INDUCED_AGINA = [
        (0,'Yes'),
        (1,'No')
    ]

    SLOPE = [
        (0,'Upsloping'),
        (1,'Flat'),
        (2,'Downsloping')
    ]

    THALLIUM_STRESS_TEST_RESULTS = [
        (0,'Normal'),
        (1,'Fixed defect'),
        (2,'Reversible defect'),
        (3,' Not described')
    ]

    id = models.UUIDField(editable=False, primary_key=True, default=uuid.uuid4, unique=True)
    age = models.IntegerField()
    sex = models.IntegerField(choices=SEX, default=0)
    chest_pain_type = models.IntegerField(choices=CHEST_PAIN_TYPE, default=0)
    resting_blood_pressure = models.IntegerField()
    serum_cholesterol = models.IntegerField()
    fasting_blood_sugar_level = models.IntegerField(
        choices=FASTING_BLOOD_SUGAR_LEVEL,
        default=0
          )
    resting_electrocardiographoc_results = models.IntegerField(
        choices=RESTING_ELECTROCARDIOGRAPHOC_RESULTS, 
        default=0
        )
    maximum_heart_rate = models.IntegerField()
    exercise_induced_agina = models.IntegerField(
        choices=EXERCISE_INDUCED_AGINA,
        default=0
        )
    st_depression = models.FloatField()
    slope = models.IntegerField(choices=SLOPE, default=0)
    number_of_major_vessels = models.IntegerField()
    thallium_stress_test_results = models.IntegerField(
        choices=THALLIUM_STRESS_TEST_RESULTS,
        default=0
        )
    prediction_result = models.CharField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(verbose_name='date_added', null=True, blank=True, auto_now_add=True)


    def __str__(self):
        return f'{self.id}'

templates/history.html
{% extends "block/base-template.html" %}
{% load static %}


{% block content %}
  <div class="main-content">
    <div class="header  pb-8 pt-5 pt-md-8" style="min-height: 200px; background-image: url({% static "/assets/img/theme/heart-disease-image_tcm7-170500.jpg" %}); background-size: cover; background-position: center top;">
      <div class="container-fluid">
        <div class="header-body">
          <h1 class="display-2 text-white"></h1>
        </div>
      </div>
    </div>
    <div class="container-fluid mt--7">

      <!-- Dark table -->
      <div class="row mt-5">
        <div class="col">
          <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
              <h3 class="text-white mb-0">History</h3>
            </div>
            <div class="table-responsive">
              <table class="table align-items-center table-dark table-flush">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">Prediction Result</th>
                    <th scope="col">Date</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for history in historys %}
                  <tr>
                    <th scope="row">
                      <div class="media align-items-center">
                        <div class="media-body">
                          <span class="mb-0 text-sm">{{history.prediction_result}}</span>
                        </div>
                      </div>
                    </th>
                    <td>
                      {{history.created_at}}
                    </td>
                    <td class="text-right">
                      <div class="dropdown">
                        <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fas fa-ellipsis-v"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                          <a class="dropdown-item" href="{% url 'website:results' history.pk %}">View</a>
                          <a class="dropdown-item" href="{% url 'website:delete-result' history.id %}">Delete</a>
                        </div>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      {% endblock content %}   

templates/input-data.html
{% extends "block/base-template.html" %}
{% load static %}


{% block content %}
  <div class="main-content">
    <!-- Navbar -->
    
    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 500px; background-image: url({% static "/assets/img/theme/_w850.jpg" %}); background-size: cover; background-position: center top;">
      <!-- Mask -->
      <span class="mask bg-gradient-default opacity-4"></span>
      <!-- Header container -->
      <div class="container-fluid d-flex align-items-center">
        <div class="row">
          <div class="col-lg-7 col-md-10">
            <h1 class="display-2 text-white">Monitor your Heart</h1>
            <p class="text-white mt-0 mb-5"> Early detection of heart disease can significantly improve patient outcomes by enabling timely interventions and treatments. 
          </div>
        </div>
      </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--7">
      <div class="row">
        <div class="col-xl-12 order-xl-1">
          <div class="card bg-secondary shadow">
            <div class="card-header bg-white border-0">
              <div class="row align-items-center">
                <div class="col-8">
                  {% comment %} <h3 class="mb-0">Upload CSV </h3> {% endcomment %}
                </div>
              </div>
            </div>
            <div class="card-body">
              <form id="heartForm" action="" method="POST">
                {% csrf_token %}
                <div class="pl-lg-4">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-username">Age</label>
                        {{form.age}}
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-email">Gender</label>
                        <select class="form-control form-control-alternative" required name="{{ form.sex.name }}" name="" id="">
                          {% for code, name in form.sex.field.choices %}
                          <option value="{{ code }}" {% if code == sex.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                    
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Chest Pain Type</label>
                        <select class="form-control form-control-alternative" required name="{{ form.chest_pain_type.name }}" name="" id="">
                          {% for code, name in form.chest_pain_type.field.choices %}
                          <option value="{{ code }}" {% if code == chest_pain_type.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Resting Blood Pressure (mmHg)</label>
                        {{form.resting_blood_pressure}}
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Serum Cholesrol (mg/dl)</label>
                        {{form.serum_cholesterol}}
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Fasting Blood Sugar > 120 mg/dl</label>
                        <select class="form-control form-control-alternative" required name="{{ form.fasting_blood_sugar_level.name }}" name="" id="">
                          {% for code, name in form.fasting_blood_sugar_level.field.choices %}
                          <option value="{{ code }}" {% if code == fasting_blood_sugar_level.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                  </div> <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Resting Electrocordiagraphic Results</label>
                        <select class="form-control form-control-alternative" required name="{{ form.resting_electrocardiographoc_results.name }}" name="" id="">
                          {% for code, name in form.resting_electrocardiographoc_results.field.choices %}
                          <option value="{{ code }}" {% if code == resting_electrocardiographoc_results.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">Maximum Heart Rate Achieved</label>
                        {{form.maximum_heart_rate}}
                      </div>
                    </div>
                  </div> <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Exercise Include Angina</label>
                        <select class="form-control form-control-alternative" required name="{{ form.exercise_induced_agina.name }}" name="" id="">
                          {% for code, name in form.exercise_induced_agina.field.choices %}
                          <option value="{{ code }}" {% if code == exercise_induced_agina.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name">ST Depression</label>
                        {{form.st_depression}}
                      </div>
                    </div>
                  </div> <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Slope of the Peak Exercise ST Segment</label>
                        <select class="form-control form-control-alternative" required name="{{ form.slope.name }}" name="" id="">
                          {% for code, name in form.slope.field.choices %}
                          <option value="{{ code }}" {% if code == slope.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-last-name"> Number of Major Vessels (0-4)</label>
                        {{form.number_of_major_vessels}}
                      </div>
                    </div>
                  </div> <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Thallium Stress Test Result</label>
                        <select class="form-control form-control-alternative" required name="{{ form.thallium_stress_test_results.name }}" name="" id="">
                          {% for code, name in form.thallium_stress_test_results.field.choices %}
                          <option value="{{ code }}" {% if code == thallium_stress_test_results.value %}selected{% endif %}>{{ name }}</option>
                          {% endfor %} 
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="text-right">
                  <button type="submit" class="btn btn-info">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>

      <script>
        document.getElementById('heartForm').addEventListener('submit', async function(event) {
          event.preventDefault();
      
          const form = new FormData(this); 
      
         
          const formData = {};
          form.forEach((value, key) => {
            formData[key] = value;
          });
      
          try {
            
            const response = await fetch('http://127.0.0.1:8000/api/heart-api/', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
              },
              body: JSON.stringify(formData)
            });
      
            const result = await response.json();
      
            if (response.ok) {
             
              window.location.href = `/prediction-results/${result.id}/`;
          } else {
             
              console.error(result);
          }
      
          } catch (error) {
            console.error('Error:', error);
          }
        });
      </script>
      
 {% endblock content %}   

templates/results.html
{% extends "block/base-template.html" %}
{% load static %}


{% block content %}
  <div class="main-content ">

    <!-- Header -->
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 100px;">
    </div>
    <!-- <span class="mask bg-gradient-default opacity-4"></span> -->
    <!-- Page content -->
    <div class="container-fluid mt--9 " >
      <div class="row">
        <div class="col-xl-12 order-xl-2 mb- mb-xl-0">
            
            <div class="card card-profile shadow">
              <div class="card-body pt-0 pt-md-4">
                  <div class="row">
                      <div class="col">
                          <div class="card-profile-stats d-flex justify-content-center">
                              <h1 class="mb-4">Prediction Results</h1>
                          </div>
                      </div>
                  </div>
          
                  <!-- Create rows and columns to organize the display -->
                  <div class="container">
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Age:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.age }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Gender:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_sex_display }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Chest Pain Type:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_chest_pain_type_display }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Resting Blood Pressure:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.resting_blood_pressure }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Serum Cholesterol:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.serum_cholesterol }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Fasting Blood Sugar > 120 mg/dl:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_fasting_blood_sugar_level_display }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Resting Electrocardiographic Results:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_resting_electrocardiographoc_results_display }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Maximum Heart Rate Achieved:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.maximum_heart_rate }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Exercise Induced Angina:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_exercise_induced_agina_display }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">ST Depression:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.st_depression }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Slope of the Peak Exercise ST Segment:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_slope_display }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Number of Major Vessels (0-4):</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.number_of_major_vessels }}</p>
                          </div>
                      </div>
          
                      <div class="row mb-3">
                          <div class="col-6">
                              <p class="font-weight-bold">Thallium Stress Test Result:</p>
                          </div>
                          <div class="col-6 text-right">
                              <p>{{ results.get_thallium_stress_test_results_display }}</p>
                          </div>
                      </div>
                  </div>
          
                  <hr class="my-4" />
          
                  <p class="text-center font-weight-bold">Prediction Result: {{ results.prediction_result }}</p>
              </div>
          </div>
          

      {% endblock content %}   